### ISSUE TITLE
number of common peaks when using 'joinPeaksGnps'

### ISSUE THREAD

**Issue by mar-garcia** [rformassspectrometry/MetaboAnnotation#119]
Hi!!

When using the function `MatchForwardReverseParam` together with the GNPS functions (i.e., MAPFUN = joinPeaksGnps, FUN = gnps) to get the number of matching peaks and presence ratio (apart from the similarity score) it seems the algoritm is only considering the common peaks based on their m/z values and ignoring the common peaks based on their neutral losses. It would be nice that when using the GNPS functions the calculation of the number of matching peaks would consider the matches by both m/z and neutral losses.
Here an example:

```r
spd <- DataFrame(
  precursorMz = c(623.1618, 609.1825)
)
spd$mz <- list(
  c(300.0276, 315.0511),
  c(242.0585, 286.0483, 301.0718)
)
spd$intensity <- list(
  c(20, 100),
  c(1, 10, 100)
)
sps <- Spectra(spd)
mtch <- matchSpectra(sps[1], sps[2], 
                     param =  MatchForwardReverseParam(requirePrecursor = FALSE, tolerance = 0.01,
                                                       THRESHFUN = function(x) which(x >= 0), 
                                                       MAPFUN = joinPeaksGnps, FUN = gnps))
res <- data.frame(spectraData(mtch))
res[,c("score", "reverse_score", "presence_ratio", "matched_peaks_count")]
      score reverse_score presence_ratio matched_peaks_count
1 0.9889945             0              0                   0

jo <- join_gnps(x = mz(sps)[[1]], y = mz(sps)[[2]], sps$precursorMz[1], sps$precursorMz[2], tolerance = 0.01)  
jo$x[which(!is.na(jo$x) & !is.na(jo$y))]
[1] 1 2
jo$y[which(!is.na(jo$x) & !is.na(jo$y))]
[1] 2 3
```

These 2 spectras have in common the neutral losses 323.1342 and 308.1107 (they don't have in common any m/z value within their fragments).
Therefore, I would expect that since we are applying the "joinPeaksGnps" and "gnps" functions, the "presence_ratio"  should be > 0 (maybe 4/5 or 2/2.5 = 0.8?), and the "matched_peaks_count" = 2.

**Comment by jorainer** [comment]
@mar-garcia , can you please confirm that the fixed version works for you? you would need to install it from github using `BiocManager::install("RforMassSpectrometry/MetaboAnnotation", ref = "jomain")`.

**Comment by mar-garcia** [comment]
Super! I would say now it's working! Thanks a lot!! :)
