### ISSUE TITLE
Sticker for MetaboAnnotation

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MetaboAnnotation#17]
We need a sticker for MetaboAnnotation. I thought maybe Sherlock Holmes with a loupe? searching for metabolites? Open for suggestions and alternative ideas @michaelwitting @andreavicini !

**Comment by michaelwitting** [comment]
Yes, I think that would fit.

**Comment by jorainer** [comment]
I found the time to start working on the sticker. That's what I've made so far: comments/improvements/suggestions @michaelwitting @andreavicini ?

![MetaboAnnotation](https://user-images.githubusercontent.com/5506112/128312982-4a92ecdb-a6f4-418f-b062-3066fba79ac3.png)

**Comment by andreavicini** [comment]
It looks very nice to me! :)

**Comment by jorainer** [comment]
Or better with a brown lower border?

![MetaboAnnotation](https://user-images.githubusercontent.com/5506112/128350459-9fe61246-452a-47ad-aaa3-7a49998cd718.png)

**Comment by jorainer** [comment]
OK, I think I found the version I like most: with that we have all the color brownish/orange/yellow. I think this one looks more *consistent*.

![MetaboAnnotation](https://user-images.githubusercontent.com/5506112/128391348-0b0032f5-9e35-496d-ba55-e8b09cf5a2ec.png)
