### ISSUE TITLE
Implement a Matched object for SummarizedExperiment

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MetaboAnnotation#20]
We should also implement a `matchMz` for `SummarizedExperiment`. That method should do the matching based on the `DataFrame` in `rowData(x)` (which is expected to contain e.g. the feature definitions with m/z and rt). I think this will then however also require a new object extending `Matched` (e.g. a `MatchedSE` or `MatchedSummarizedExperiment`).

**Comment by michaelwitting** [comment]
I would call it `MatchesSummarizedExperiment`
