### ISSUE TITLE
Consistency in parameter naming

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MetaboAnnotation#32]
Currently we have parameters `mzColumn`, `massColumn` and `rtColumn` for `matchMz` but methods `addMatches` and `filterMatches` have parameters `queryColname` and `targetColname`. I would suggest that we either call them `*Column` or `*Colname`, but not have both. @andreavicini , any preference?

**Comment by andreavicini** [comment]
Yes, you are right. Both appear fine to me. `*Colname` maybe makes clearer that we want the name and not the column itself but I think that also `*Column` wouldn't cause confusion and it's slightly shorter.

**Comment by jorainer** [comment]
Hm, I think you're right - `*Colname` maybe is more explicit. I'll change to that.
