### ISSUE TITLE
retention time in MatchForwardReverseParam

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/MetaboAnnotation#35]
Wouldn't it make sense to be able to match retention time directly in `MatchForwardReverseParam` like in `Mass2MzRtParam`?
I have our in house database with (for now) MS1 and RT for all compounds and I match to CAMERA pseudo-spectra. In that case it makes sense to also match the RT.
For now I managed to use `filterMatches`:

```R

mp <- MatchForwardReverseParam(ppm = 30)
mtches <- matchSpectra(peaklist_spectra_joined, DB_synapt, param = mp)

# Match RT
rt_tol <- 60*0.2
keep_idx <- abs(query(mtches)$rtime[mtches@matches$query_idx] - target(mtches)$rtime[mtches@matches$target_idx]) < rt_tol
keep_idx <- which(keep_idx)

mtches_rt <- filterMatches(mtches, index = keep_idx, keep = TRUE)
```

**Comment by jorainer** [comment]
hm, good point. I'll have a look into it. We could have an `rt` and `rtTolerance` parameter in there and then only match that if it is available. Alternatively, we could have an `MatchForwardReverseRtParam` that adds the RT matching in addition to the spectra matching.

**Comment by michaelwitting** [comment]
I would prefer a new param object, though the names are getting quite long now? ;-)

**Comment by jorainer** [comment]
I had a look at the code of the matching function. Akthough I would also prefer a new param object for this, we could avoid code redundancy if we simply added a `rt` and `toleranceRt` parameter to `CompareSpectraParam`. The default would be `rt = numeric()` and no rt comparison would be performed, if `rt = numeric(1)` we could simply have an additional `filterRt` call within the loop. Note however that if retention times are not provided in target (e.g. for MassBank etc) you would never get a hit!

Would this be OK for you @michaelwitting @stanstrup ?

**Comment by stanstrup** [comment]
Works for me. Default of `rt = Inf` would be my suggestion.
