### ISSUE TITLE
filter based on reverse score in MatchForwardReverseParam?

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/MetaboAnnotation#37]
If you are matching spectra to MS1 data doesn't the reverse score make most sense?
If so It would be useful to be able to access the reverse score in `THRESHFUN`.
You could also imagine you'd want to filter on number of common peaks or peak presence ratio.

**Comment by jorainer** [comment]
couldn't you simply do that by replacing `query` with `target`?

**Comment by stanstrup** [comment]
Yes, I suppose so. But the downstream workflow would be confusing and the presence ratio would be different I guess.

I can see how it would be messy but being able to define a threshold for each calculated parameter would make sense to me...

**Comment by jorainer** [comment]
Both the forward and reverse score are reported - would it be possible to filter (subset) the `MatchedSpectra` object after the `matchSpectra` call? Maybe using a more relaxed filter in `THRESHFUN` and then a more stringent on the reported reverse score?

**Comment by stanstrup** [comment]
Yes that is what I am doing now. With the speed increase that now works OK:

```r
keep_idx <- mtches@matches$reverse_score >0.7
keep_idx <- which(keep_idx)

mtches <- filterMatches(mtches, index = keep_idx, keep = TRUE)
```


Feel free to close if you consider this better handled manually like this.

**Comment by jorainer** [comment]
Would it help to have a `THRESHFUN_REVERSE` parameter in `MatchForwardReverseParam` that allows to define a function to filter the matches that passed `THRESHFUN` based on the reverse score?

**Comment by stanstrup** [comment]
Yes! That would be convenient and what I was hoping for.

**Comment by jorainer** [comment]
Please check the updated version - which should also run on R 4.0.

**Comment by stanstrup** [comment]
Works. Thanks!
