### ISSUE TITLE
matchSpectra -- Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by jmbadia** [rformassspectrometry/MetaboAnnotation#66]
Just reporting that ...
The `matchSpectra()` function throws randomly the _Error in x$.self$finalize() : attempt to apply non-function_. Result seems unaltered  independently of the number of errors obtained so I guess it is caused by the same harmless garbage collector #issue-329840320 [reported for xcms3](https://github.com/sneumann/xcms/issues/288#issue-329840320) ()   
```
mtches2 <- matchSpectra(query = pest_ms2, target = be[2000:3000],
+                        param = CompareSpectraParam(requirePrecursor = TRUE,
+                                                    ppm = 10))
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```

**Comment by jorainer** [comment]
Thanks for reporting. And yes, this all comes from the `mzR` (proteowizard) code. As you said, AFAIK this does not affect results or data in anyway, but can be surely disturbing.

Unfortunately we can't do much to fix it, thus I'm closing the issue.
