### ISSUE TITLE
validateMatchedSpectra crashes

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboAnnotation#73]
`validateMatchedSpectra` crashes if first a match with multiple matches is selected and in the table a match in rows 2 or higher is selected and then a feature with only a single match is selected.

**Comment by jorainer** [comment]
hm, I'll look into that.

**Comment by jorainer** [comment]
it's strange. the index in the table should be resetted to 1 when a new query spectrum is selected - but apparently that's not happening.

**Comment by jorainer** [comment]
@michaelwitting can you please test again with the current master? It worked for me, but better to have a second independent test.

**Comment by michaelwitting** [comment]
Tested it. Working!

**Comment by jorainer** [comment]
Great - I pushed it now also to BioC
