### ISSUE TITLE
Error when matching ion modes

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboAnnotation#77]
I receive the following error `Error: subscript contains invalid names` when calling `matchedData` on the `Matched` object in the attached .rds file.
[ms1ionmodematching.zip](https://github.com/rformassspectrometry/MetaboAnnotation/files/8404180/ms1ionmodematching.zip)

**Comment by jorainer** [comment]
It works for me - could be this was fixed in PR #76 (issue #69). Please update `MetaboAnnotation` from github (`BiocManager::install("RforMassSpectrometry/MetaboAnnotation")` and try again (could be this version is not yet available on BioC - there is some days delay sometimes).

**Comment by michaelwitting** [comment]
Indeed that was the problem. Too fast development in `MetaboAnnotation` at the moment ;-)
