### ISSUE TITLE
packages for function validateMatchedSpectra

### ISSUE THREAD

**Issue by chufz** [rformassspectrometry/MetaboAnnotation#78]
Currently, the packages 'shiny', 'shinyjs', 'DT' and 'plotly' are not installed with MetaboAnnotation, but are required for the `validateMatchedSpectra` function. Should these dependencies be included or is there a reason to keep them separate?

**Comment by jorainer** [comment]
If possible I would like to keep them separate. These will only be needed for this one function and we shouldn't require all package users to depend on all these packages if they are *just* using the core functionality of the package. Keeps the package dependency low and easier to maintain.

We do a similar thing in `Spectra`: the HDF5 functionality and mzR/proteowizard are not required packages. They are suggested. This saves us from potential installation problems with these packages (that can happen on some platforms/compiler versions).

**Comment by jorainer** [comment]
And note that also suggested packages could be automatically installed with:

```r
BiocManager::install("MetaboAnnotation", dependencies = c("Depends", "Imports", "Suggests"))
```
